### ISSUE TITLE
Send via web deletes file name after '

### ISSUE THREAD

**Issue by EmmanuelMess** [trebleshot/android#105]
**Describe the bug**
Send via web deletes file name after " ' "

**To Reproduce**
1. Send a file named "a'thing.png"
2. You recieved "a"

**Environment (please complete the following information):**
 - Android version: Android 7.1.2 
 - Language: Spanish
 - App version 1.4.2
 - Device Model and Brand LG K11-α

**Comment by velitasali** [comment]
Thanks for reporting. I am able to reproduce this.

**Comment by velitasali** [comment]
Issue caused by https://github.com/NanoHttpd/nanohttpd/issues/292

**Comment by EmmanuelMess** [comment]
> Issue caused by [NanoHttpd/nanohttpd#292](https://github.com/NanoHttpd/nanohttpd/issues/292)

I think that a better issue to reference is NanoHttpd/nanohttpd#1 as that one is marked as "bug" and not enhancement and directly targets single quotes.

**Comment by EmmanuelMess** [comment]
> Issue caused by [NanoHttpd/nanohttpd#292](https://github.com/NanoHttpd/nanohttpd/issues/292)

How is unicode handled? NanoHttpd/nanohttpd#292is marked as enhancement, should names be converted to an escaped string version?

**Comment by velitasali** [comment]
I don't think the charset is the issue here. This happens while the header is being parsed. 

Normally in a PHP-like scenario, the file would be uploaded to a temporary location and file name would be parsed as it is and if escaped characters needed to be added, they would be added manually. 

Looking at this line where the file name is defined:
https://github.com/genonbeta/TrebleShot/blob/45f78b1b27fab3599acefc10128207b304ba03ff/app/src/main/java/com/genonbeta/TrebleShot/service/WebShareServer.java#L125

And `session` variable predefined:
https://github.com/genonbeta/TrebleShot/blob/45f78b1b27fab3599acefc10128207b304ba03ff/app/src/main/java/com/genonbeta/TrebleShot/service/WebShareServer.java#L92

It looks like the best choice is to modify nanohttpd.
https://github.com/NanoHttpd/nanohttpd/blob/fd80618e93d17f8f05e11006eaa048a22213714d/core/src/main/java/org/nanohttpd/protocols/http/NanoHTTPD.java#L135

I am not sure if they would accept a patch though.
