### ISSUE TITLE
Usability drawbacks and their explanation in comparison to nitroshare

### ISSUE THREAD

**Issue by matu3ba** [trebleshot/android#122]
1. I dont understand why GPS and adding hotspot/changing device settings are needed to establish a connection. This feels like google asking for your data.
2. Further I dont understand why the QR code is needed at all in a local network or with a hotspot. The router/hotspot should already block all packets on a local network or the network is already broken (and thus the IP useless, since the attacker knows how to talk to all devices).
Does the QR code contain a secret for the connection setup?

May anybody explain?

**Comment by denilsonsa** [comment]
Hi, I'm just a TrebleShot user, but I think I know one answer.

[Since Android 8.0 (API level 26), apps using Wi-Fi scanning are required to request access to Location.](https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-restrictions) That's because scanning the available Wi-Fi networks is enough to get a pretty accurate device location by checking against some Wi-Fi database. [This permission was introduced in TrebleShot when the hotspot feature was implemented.](https://github.com/trebleshot/android/commit/7d23d55f4b5e7900601c964cedc962215f87884e)

That's all that I know, I'll leave the rest of answers to someone else. (Or you can also look at the source-code.)

**Comment by damascene** [comment]
@denilsonsa so now they can have wifi information and GPS information too?

**Comment by mubashir-rehman** [comment]
> @denilsonsa so now they can have wifi information and GPS information too?

I would rather interpret as "They require wifi and GPS permission to work." Just like all other local file sharing apps.

**Comment by velitasali** [comment]
Yes, QR codes contain valuable information. In the case of a WiFi connection, it shows the IP location of the device. If both devices have a working Multicast DNS including the network support, it may not be needed, but if mDNS doesn't work or fails to resolve, then, QR codes can be of good use.

In the case of hotspot connections, it contains the SSID, network password, and PIN.
