### ISSUE TITLE
Use existing system hotspot name and password or create a open hotspot

### ISSUE THREAD

**Issue by UddipakBhuyan** [trebleshot/android#127]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when needing to retype in my password when connecting to hotspot to share when creating a hotspot using the trebleshot. 

**Describe the solution you'd like**
I would like to trebleshot to use the existing hotspot name and password from the system. Or just provide a way to create a non password protected hotspot with the ability to disable mobile data.

**Describe alternatives you've considered**
other apps such as xender and shareit have this ability

**Comment by mubashir-rehman** [comment]
This feature is already available.

**Comment by UddipakBhuyan** [comment]
Thanks! It works when I scan for the device when the system hotspot feature is turned on. The UI is a bit unintuitive for someone used to the other simple apps with fewer features. This app needs some kind of tutorial or hints at each step for a new user.

Also I understand when the app creates a new hotspot by itself, not using the one on the system is useful, in cases where the user may not want to share the hotspot and password of the system. But I would like the ability to turn the sytem hotspot on from the app itself without opening the system settings. And also mobile data disabled while sharing would be useful also.

> This helps if you have trebleshot on other device too.
Does this app work without trebleshot on the other device? Other than share on browser which I use a lot when connecting my laptop

**Comment by mubashir-rehman** [comment]
The share on browser also works when other phone doesn't have Trebleshot installed. However, the other phone should have a browser to get benefit from that.
I have never ever tried using Trebleshot with Bluetooth.
Also, there is an option named "Need a helping hand" on the screen where you select network. This is the first option and is there to help setup. It has instructions and is the most helpful way to understand what type of Connection I need. However, most people ignore it because it is not separate from other options. It is first options out of given 5 options.(Check this please let us know if there is improvement needed. of course it is needed. However, kindly explain how would it be more intuitive, so that developers can look for the best possible option.)

**Comment by mubashir-rehman** [comment]
I am gonna start a new issue for the problem shred by you in second paragraph, cuz I think it should be different issue cuz it is different feature request If the developer finds that it is the same as this they would merge it.
