### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by erneandroid** [trebleshot/android#168]
Slowly when select files to send ( like images ) that can be much images, this send one by one and this make it slowly

**Comment by mubashir-rehman** [comment]
@erneandroid This is the default nature for any file transfer on any platform. It is would be difficult to do parallel sending and there would be limitations. One thing that is possible is to archive all the files in one single zip and send them as one file. Which Trebleshot already does for webshare. It can be improved but because of lack of my knowledge, i can't make much comments on it.

**Comment by erneandroid** [comment]
Cool, bro thx for comment

**Comment by velitasali** [comment]
@erneandroid If you are referring to the slow transfer speed when sending multiple files with small sizes (such as images), it was a design limitation of the previous versions such as 1.4.2 and below. 

All and all, I will make performance improvements where they are plausible. Hope this helps :)

**Comment by erneandroid** [comment]
> @erneandroid If you are referring to the slow transfer speed when sending multiple files with small sizes (such as images), it was a design limitation of the previous versions such as 1.4.2 and below.
> 
> All and all, I will make performance improvements where they are plausible. Hope this helps :)

Of course it's help too much
