### ISSUE TITLE
Web Zip Compression Level

### ISSUE THREAD

**Issue by erneandroid** [trebleshot/android#172]
In web share add support to choose between differents levels of compression this can help when the file have to much weight.
I will find some source code project about zip and edit this issue.
:)

**Comment by velitasali** [comment]
The zip feature is only there because it was the easiest option when it comes to downloading multiple files. I don't think adding support for compression levels makes sense because any level of compression will affect the download speed as the server (sender) directly writes the zip input as an HTTP output. Also, that feature is not related to transferring files and any other file manager would do a better job at compressing zip files.

**Comment by mubashir-rehman** [comment]
@erneandroid compression is useless feature unless there is a lot of text or files that can be compressed. While most of the user send or share media files which are already on compressed form and further external compression just increases the processing time and file size instead of decreasing it. This is what I have experienced, your experience and use case might be different from mine. and I would love to hear from you

**Comment by velitasali** [comment]
@mubashir-rehman I agree. I don't think this feature would be useful. 

@erneandroid You can close the issue if you don't have anything to add :)
