### ISSUE TITLE
let friends download the apk they want

### ISSUE THREAD

**Issue by adbenitez** [trebleshot/android#98]
**Is your feature request related to a problem? Please describe.**
It is hard to share apks with several friends at the same time, also it is hard to find out if one of them has a more updated version of the apps we have in common. 

**Describe the solution you'd like**
It would be easier if Treble Shot could share a list of my installed apks and their versions with other Treble Shot users, so my friends can see my apks as some kind of store and pick what they want by themselves instead of me having to manually send them, also Treble Shot could compare the versions of my apks with their istalled apks and if I have a more recent update of an apk they have, Treble Shot could notify this and allow my friends to update their apps easily (including Treble Shot itself)

**Additional context**
This scenario is pretty common here in Cuba where internet access is expensive and people share apks with friends offline, people here use a privative apk similar to Treble Shot called Zapya that has the feature described above, I think Treble Shot has the potential to replace such app.

**Comment by velitasali** [comment]
I understand the need for this feature, but this feature is not possible without a big design overhaul (which I don't want to do). Also, sending and receiving APK files have become a challenge after Google introduced the AAB format. F-Droid may be a better fit for sending APK files since it mostly focuses on non-Play versions of apps.
